### PR TITLE
Add OpenAIP Datasets to AvareX 

### PR DESCRIPTION
**Pull request by MatthewReed303**
This PR adds an OpenAIP section to the menu where you can select the country and download the dataset for the entire country directly from OpenAIP. ( If any data is out of date, user is best to update it via OpenAIP API for there country and redownload new dataset ) 

Once the dataset is download, the JSON is parsed and converts it to avareX data structure and adds it to a new database called openaip.db with same structure as the main.db

The add openAIP to AvareX button adds the openaip.db data to main.db and keeps the openaip.db data in the main.db synced.

### CODE REVIEW

**Comment by no-lex** [comment]
I downloaded this fork and tried it out on my development environment.

Unfortunately, I can't seem to get the data to load-- it gets stuck with a grayed out screen and loading spinner. 

There also appears to be a draw overflow issues running on my emulated Android device:
 - In portrait mode, the "Add OpenAIP to AvareX" button gets cut off the right side of the window
 - In landscape mode, there isn't enough area to render the bottom of the menu, and there does not appear to be a way to scroll.
 
Screenshot_20241220_215103
Screenshot_20241220_214150

I tested the PR on my Ubuntu 22.04 desktop running Flutter 3.24.5, and on an Android emulator (1920x1080, Android 15).

Hopefully this helps. If there is something I am misconfiguring, please let me know.

**Comment by apps4av** [comment]
If you like to add openaip data, add it to the monthly main.db preparation
under apps4av/data. Adding data in the app is not the way the app is
designed.
This will be rejected but thanks for the initiative.

**Comment by MatthewReed303** [comment]
@no-lex sorry was supposed to remove the US option as it will conflict with existing US data built in main.db, the US takes quite a while to download and add to main.db ( 25mb but it does work if you wait ) If you try NZ, AUS etc will load a lot faster. I will fix up these UI issues, I just installed the APK onto my phone and see the issues, I was using a tablet. 

@apps4av I did consider adding it directly to main.db under apps4av/data but we can't add everything there as it would make the main.db huge. There is also no way for the user to just select there country and would have to download a complete huge main.db, it's already 50mb with just the US. I thought giving the user the option to just download there country and add it from within app would be the best solution.

**Comment by no-lex** [comment]
I think part of the issue is that the loading spinner does not convey the actual progress being made -- for a download that may take minutes, it is probably better to indicate the actual progress (like the download menu does). My understanding is that spinners with no progress indication are suitable for loading times under about ten seconds.

**Pull request closed without merging**
